export const YOU_GOTTA_POINT_QUESTIONS = [
    "Most likely to have a 'thing' for mermaids.",
    "Most likely to share a two-horse costume with.",
    "Person most likely to outlive you.",
    "Knows the most about Star Wars.",
    "Give best hugs.",
    "Best chance at beating in a fight.",
    "Most likely to own leather pants.",
    "Has the most speeding tickets.",
    "Most likely to scream if they saw a rat.",
    "Would want on your team while playing a trivia game.",
    "Most likely an organ donor.",
    "Person you like best.",
    "Probably a dog lover.",
    "Die first in a horror film.",
    "Person you'd want to be trapped on island with.",
    "Happiest in general.",
    "Seen the most Disney movies.",
    "Would make the best vampire.",
    "Should have their own reality show.",
    "Most addicted to their phone.",
    "Would kick butt in Game of Thrones.",
    "Person you'd eat if you all crashed in the alps.",
    "Want to know better.",
    "Most likely to win a spelling bee.",
    "Told the most secrets to.",
    "Says bro the most.",
    "The worst at this game.",
    "Worst dancer.",
    "Likes the worst movies.",
    "Best Politician.",
    "Prettiest hands.",
    "Most likely give a high five to.",
    "Person who, if they switched bodies with you, would really screw up your life.",
    "Make a great James Bond.",
    "Noisiest person.",
    "Survive zombie apocalypse.",
    "Most likely to refer to themselves as a 'foodie'.",
    "Most likely to be rich.",
    "Most likely to donate money to charity.",
    "Most likely to marry first.",
    "Most likely to kill someone.",
    "Most likely to get in a fight.",
    "Most likely to punch a wall.",
    "Most likely to die first in a zombie apocalypse.",
    "Most likely to run away and join the circus.",
    "Most likely to spend all their money on something stupid.",
    "Most likely to die in a blaze of glory.",
    "Most likely to have an existential crisis.",
    "Most likely to have a collection of vintage vinyl records.",
    "Most likely to spontaneously break out into song and dance.",
    "Person most likely to become a famous chef.",
    "Knows all the lyrics to every Taylor Swift song.",
    "Gives the best advice.",
    "Best at keeping a secret.",
    "Most likely to own a pet snake.",
    "Has the most exotic taste in food.",
    "Most likely to jump out of a plane for fun.",
    "Would be the first to try out for a reality TV show.",
    "Most likely to win a Nobel Prize.",
    "Person you'd trust with your life.",
    "Probably has a secret talent nobody knows about.",
    "Would survive the longest on a deserted island.",
    "Person you'd want to be stranded with during a blizzard.",
    "Always knows the latest gossip.",
    "Seen every episode of Friends multiple times.",
    "Would win in a karaoke competition.",
    "Should write a book about their life.",
    "Most likely to be a famous actor/actress.",
    "Would make the best detective.",
    "Person you'd call at 3 AM if you needed help.",
    "Most likely to start their own business.",
    "Most likely to become a world traveler.",
    "Told the best ghost stories.",
    "Owns the most bizarre collection of items.",
    "The best at planning surprise parties.",
    "Would survive the longest in the wilderness.",
    "Most likely to win in a staring contest.",
    "Would excel as a motivational speaker.",
    "Has the most contagious laugh.",
    "Most likely to become a professional athlete.",
    "Person you'd want to road trip across the country with.",
    "Makes the best homemade cookies.",
    "Most likely to win a dance-off.",
    "Would be the best stand-up comedian.",
    "Most likely to start their own YouTube channel.",
    "Would be a great travel buddy.",
    "Most likely to become a fashion icon.",
    "Would excel as a motivational speaker.",
    "Has the best taste in music.",
    "Most likely to become a famous artist.",
    "Would win in a debate competition.",
    "Person you'd trust to plan your wedding.",
    "Most likely to win a game of charades.",
    "Most likely to own a pet reptile.",
    "Best at solving riddles.",
    "Person most likely to become a famous author.",
    "Knows the most about ancient civilizations.",
    "Gives the best pep talks.",
    "Best at keeping calm in stressful situations.",
    "Most likely to own a vintage car.",
    "Has the most encyclopedic knowledge of music.",
    "Most likely to climb Mount Everest.",
    "Would be the first to explore outer space if given the chance.",
    "Most likely to win a gold medal in the Olympics.",
    "Person you'd trust to plan a surprise party.",
    "Probably owns the most colorful wardrobe.",
    "Would win in a hot dog eating contest.",
    "Person you'd want to be stranded with in a haunted house.",
    "Always knows the best spots for stargazing.",
    "Seen every episode of The Office multiple times.",
    "Would make the best tour guide in their hometown.",
    "Should start their own podcast.",
    "Most likely to become a renowned scientist.",
    "Would excel as a motivational speaker.",
    "Person you'd trust to give you fashion advice.",
    "Most likely to become a professional athlete.",
    "Most likely to win a game of chess.",
    "Told the best jokes.",
    "Has the most adventurous palate.",
    "The best at navigating through a city without GPS.",
    "Would survive the longest in a survival reality show.",
    "Most likely to win in a thumb war.",
    "Would make the best travel companion.",
    "Has the most contagious laughter.",
    "Most likely to become a famous actor/actress.",
    "Person you'd want to be your partner in a dance competition.",
    "Makes the best homemade pizza.",
    "Most likely to win in a game of Scrabble.",
    "Would excel as a stand-up comedian.",
    "Most likely to start their own business empire.",
    "Would be a great mentor to others.",
    "Most likely to win a game of poker.",
    "Would make the best teacher.",
    "Has the best taste in movies.",
    "Most likely to become a famous painter.",
    "Would win in a game of mini golf.",
    "Person you'd trust to plan a road trip.",
    "Most likely to win a talent show.",
    "Most likely to own a pet reptile.",
    "Best at solving riddles.",
    "Person most likely to become a famous author.",
    "Knows the most about ancient civilizations.",
    "Gives the best pep talks.",
    "Best at keeping calm in stressful situations.",
    "Most likely to own a vintage car.",
    "Has the most encyclopedic knowledge of music.",
    "Most likely to climb Mount Everest.",
    "Would be the first to explore outer space if given the chance.",
    "Most likely to win a gold medal in the Olympics.",
    "Person you'd trust to plan a surprise party.",
    "Probably owns the most colorful wardrobe.",
    "Would win in a hot dog eating contest.",
    "Person you'd want to be stranded with in a haunted house.",
    "Always knows the best spots for stargazing.",
    "Seen every episode of The Office multiple times.",
    "Would make the best tour guide in their hometown.",
    "Should start their own podcast.",
    "Most likely to become a renowned scientist.",
    "Would excel as a motivational speaker.",
    "Person you'd trust to give you fashion advice.",
    "Most likely to become a professional athlete.",
    "Most likely to win a game of chess.",
    "Told the best jokes.",
    "Has the most adventurous palate.",
    "The best at navigating through a city without GPS.",
    "Would survive the longest in a survival reality show.",
    "Most likely to win in a thumb war.",
    "Would make the best travel companion.",
    "Has the most contagious laughter.",
    "Most likely to become a famous actor/actress.",
    "Person you'd want to be your partner in a dance competition.",
    "Makes the best homemade pizza.",
    "Most likely to win in a game of Scrabble.",
    "Would excel as a stand-up comedian.",
    "Most likely to start their own business empire.",
    "Would be a great mentor to others.",
    "Most likely to win a game of poker.",
    "Would make the best teacher.",
    "Has the best taste in movies.",
    "Most likely to become a famous painter.",
    "Would win in a game of mini golf.",
    "Person you'd trust to plan a road trip.",
    "Most likely to win a talent show.",
] as const;


export const FACE_VALUE_QUESTIONS = [
    "Show your surprise.",
    "Show your excitement.",
    "Show your disgust.",
    "Show your confusion.",
    "Show your happiness.",
    "Show your frustration.",
    "Show your fear.",
    "Show your determination.",
    "Show your admiration.",
    "Show your skepticism.",
    "Show your suspicion.",
    "Show your embarrassment.",
    "Show your anger.",
    "Show your sadness.",
    "Show your amusement.",
    "Show your anticipation.",
    "Show your satisfaction.",
    "Show your contempt.",
    "Show your love.",
    "Show your boredom.",
    "Simulate the expression of someone discovering a long-lost treasure.",
    "Show the reaction of someone realizing they've been pranked.",
    "Portray the facial expression of someone trying to solve a difficult puzzle.",
    "Illustrate the reaction of someone witnessing a breathtaking sunset for the first time.",
    "Display the expression of someone trying to hide their amusement during a serious moment.",
    "Mimic the facial expression of someone trying to stay calm during a tense negotiation.",
    "Depict the reaction of someone receiving unexpected good news.",
    "Simulate the expression of someone caught in a sudden downpour without an umbrella.",
    "Illustrate the reaction of someone encountering their greatest fear in a haunted house.",
    "Portray the facial expression of someone trying to contain their excitement while waiting for a surprise party.",
    "Show the reaction of someone trying to understand a complex scientific concept.",
    "Simulate the expression of someone experiencing a sudden epiphany.",
    "Depict the reaction of someone receiving a heartfelt apology.",
    "Illustrate the facial expression of someone trying to resist laughing during a serious moment.",
    "Portray the reaction of someone realizing they've forgotten an important deadline.",
    "Show the expression of someone trying to maintain composure while giving a public speech.",
    "Simulate the reaction of someone realizing they've accidentally sent a private message to the wrong person.",
    "Depict the facial expression of someone trying to hide their disappointment after a failed surprise.",
    "Illustrate the reaction of someone encountering an unexpected obstacle during a journey.",
    "Portray the expression of someone trying to mask their nervousness before a job interview.",
    "Show discovering a treasure.",
    "Portray being pranked.",
    "Illustrate solving a puzzle.",
    "Mimic seeing a breathtaking sunset.",
    "Display hiding amusement.",
    "Depict staying calm in negotiation.",
    "Simulate receiving unexpected good news.",
    "Show caught in sudden downpour.",
    "Portray encountering greatest fear.",
    "Illustrate containing excitement for surprise party.",
    "Mimic trying to understand complex concept.",
    "Depict sudden epiphany.",
    "Show receiving heartfelt apology.",
    "Illustrate trying not to laugh.",
    "Portray forgetting important deadline.",
    "Simulate maintaining composure during speech.",
    "Show sending private message to wrong person.",
    "Depict hiding disappointment after failed surprise.",
    "Illustrate facing unexpected obstacle.",
    "Portray masking nervousness before interview.",
    "Show witnessing miraculous event.",
    "Depict consoling friend in distress.",
    "Illustrate caught in moral dilemma.",
    "Mimic receiving conflicting advice.",
    "Portray experiencing existential crisis.",
    "Show navigating difficult conversation with loved one.",
    "Depict grappling with self-realization.",
    "Illustrate making difficult decision.",
    "Mimic experiencing moment of self-discovery.",
    "Portray confronting deepest fears.",
    "Show maintaining composure during crisis.",
    "Depict attempting forgiveness.",
    "Illustrate finding hope in dire situation.",
    "Mimic confronting past mistakes.",
    "Portray facing unexpected betrayal.",
    "Show finding meaning in chaos.",
    "Depict experiencing profound gratitude.",
    "Illustrate conveying complex emotions through art.",
    "Mimic realizing importance of self-love.",
    "Show embracing vulnerability in relationships."
] as const;


export const NUMBER_PRESSURE_QUESTIONS = [
    "Social media apps on phone",
    "Hours since you last pooped",
    "1-10, how excited would you be going to a magic show?",
    "Pancakes you would typically eat",
    "Extra ingredients you add to coffee",
    "Times you've pooped in the woods",
    "Pairs of shoes you own",
    "Times you've showered this week",
    "Countries you've visited",
    "Toppings you typically order on a pizza",
    "Miles you walk on an average day",
    "Number of cavities you have",
    "Video game consoles you own",
    "Books you've read this year",
    "Steaks you've eaten in the last month",
    "Flights you've been on in the last year",
    "Number of streaming services you pay for",
    "Seasons of the walking dead you've watched",
    "Times you go toss the gym each week",
    "When you stopped believing in Santa",
    "Every ten minutes it takes you to get to work",
    "1-10, how handy are you around the house?",
    "Partners you've had",
    "On a scale of 1 to 10, how much do you enjoy spicy food?",
    "How many times a week do you exercise?",
    "Rate your proficiency in a foreign language from 1 to 10",
    "On a scale of 1 to 10, how much do you enjoy camping?",
    "How many cups of coffee do you drink in a day?",
    "How often do you cook at home on a scale of 1 to 10?",
    "On a scale of 1 to 10, how much do you enjoy attending live music concerts?",
    "How many hours of sleep do you get on average each night?",
    "Rate your level of interest in gardening from 1 to 10",
    "On a scale of 1 to 10, how much do you enjoy watching movies?",
    "How many close friends do you have?",
    "Rate your skill level in a particular sport from 1 to 10",
    "On a scale of 1 to 10, how adventurous are you when it comes to trying new foods?",
    "How many languages can you speak fluently?",
    "Rate your satisfaction with your current job from 1 to 10",
    "On a scale of 1 to 10, how much do you enjoy hiking?",
    "How many hours a day do you spend on social media?",
    "Rate your level of patience from 1 to 10",
    "On a scale of 1 to 10, how much do you enjoy spending time with family?",
    "How many hours do you spend on leisure activities each week?",
    "Rate your ability to handle stress from 1 to 10",
    "On a scale of 1 to 10, how much do you enjoy traveling?",
    "How many pets do you have?",
    "Rate your level of interest in technology from 1 to 10",
    "On a scale of 1 to 10, how much do you enjoy attending parties?",
    "How many hours a week do you spend volunteering?",
    "Rate your level of creativity from 1 to 10",
    "How often do you go for a walk?",
    "How many cups of tea do you drink in a day?",
    "How many times a week do you eat out at restaurants?",
    "How many times have you traveled abroad?",
    "How many books do you read in a month?",
    "How many hours of TV do you watch in a week?",
    "How many times a week do you call your family?",
    "How many times have you tried a new hobby in the last year?",
    "How many times have you visited a museum or art gallery in the last month?",
    "How many different types of cuisine have you tried in the last month?",
    "How many times have you attended a live performance (e.g., concert, theater) in the last year?",
    "How many new people have you met in the last month?",
    "How many times have you donated to charity in the last year?",
    "How many hours do you spend on household chores in a week?",
    "How many times have you cooked a new recipe in the last month?",
    "How many different genres of music do you listen to regularly?",
    "How many hours do you spend outdoors in a week?",
    "How many times have you exercised with a friend in the last month?",
    "How many different sports have you tried in your lifetime?",
    "How many times have you volunteered for a community event in the last year?",
    "How many times have you attended a religious service in the last month?",
    "How many hours do you spend on a creative hobby in a week?",
    "How many times have you attended a family gathering in the last month?",
    "How many times have you visited a coffee shop in the last week?",
    "How many different languages can you speak at least a few words in?",
    "How many times have you listened to a podcast in the last week?",
    "How many times have you gone to bed before midnight in the last month?",
    "How many different types of exercise do you incorporate into your routine?",
    "How many times have you completed a DIY project in the last year?"
] as const;

export const HANDS_OF_TRUTH_QUESTIONS = [
    "Like to sing?",
    "Worked as a babysitter?",
    "Friends with an ex on Facebook?",
    "Been thrown out of a place?",
    "Fallen asleep in a movie theater?",
    "Seen Game of Thrones?",
    "Never got detention?",
    "Dislike cats?",
    "Still have wisdom teeth?",
    "Stolen someone's lunch (accidentally or on purpose)?",
    "Donated blood?",
    "Cried in a movie theater?",
    "Vomited on a plane?",
    "Been punched?",
    "Ever shoplifted?",
    "Showered today?",
    "Been in a long-distance relationship?",
    "Thrown up in public?",
    "Been in a car accident?",
    "Gotten into a fight?",
    "Snuck food into a movie theater?",
    "Cyber stalked a crush?",
    "Agreed with something Donald Trump said?",
    "Not tipped at a restaurant?",
    "Lied about my age?",
    "Shot a gun?",
    "Met a celebrity?",
    "Thought a movie was better than the book?",
    "Been mistaken for the opposite gender?",
    "Lied to your parents about where you were going?",
    "Been to an adult store?",
    "Broken a bone?",
    "Been slapped?",
    "Been robbed?",
    "Have a fear of spiders?",
    "Ever skipped school or work?",
    "Enjoy spicy food?",
    "Have traveled to more than five countries?",
    "Ever dyed your hair a wild color?",
    "Enjoy camping?",
    "Ever won a competition?",
    "Enjoy reading?",
    "Like roller coasters?",
    "Have a favorite season?",
    "Have ever performed on stage?",
    "Have ever gone skydiving or bungee jumping?",
    "Have ever ridden a motorcycle or driven a sports car?",
    "Have ever ridden a horse?",
    "Have ever gone scuba diving or snorkeling?",
    "Have ever gone zip-lining or rock climbing?",
    "Have ever been on a cruise?",
    "Have ever gone canoeing or kayaking?",
    "Enjoy doing theater or live performances?",
    "Have ever danced in public?",
    "Enjoy cooking?",
    "Have a fear of heights?",
    "Have ever ridden a roller coaster?",
    "Have ever participated in a talent show?",
    "Have ever attended a music concert?",
    "Have ever been on a road trip?",
    "Enjoy outdoor activities?",
    "Have a fear of public speaking?",
    "Have ever performed karaoke?",
    "Have ever gone on a blind date?",
    "Enjoy watching horror movies?",
    "Have ever tried a food challenge?",
    "Have a fear of flying?",
    "Enjoy playing board games?",
    "Have ever gone on a camping trip?",
    "Have ever gotten a tattoo?",
    "Enjoy going to the beach?",
    "Have ever gone on a spontaneous trip?",
    "Have ever ridden a bicycle in the city?",
    "Have ever tried extreme sports?",
    "Enjoy going to amusement parks?",
    "Have ever attended a costume party?",
    "Enjoy attending live sports events?",
    "Have ever tried a new hobby on a whim?",
    "Have ever gone skinny-dipping?",
    "Enjoy hiking in the mountains?",
    "Have ever taken a road trip with friends?",
    "Enjoy attending music festivals?",
    "Have ever gone on a group vacation?",
    "Enjoy watching reality TV shows?",
    "Have ever tried exotic cuisine?",
    "Enjoy attending comedy shows?",
    "Have ever gone on a long train journey?",
    "Enjoy gardening or tending to plants?",
    "Have ever gone on a ghost tour?",
    "Enjoy going to museums or art galleries?",
    "Have ever gone on a hot air balloon ride?",
    "Enjoy attending food festivals?",
    "Have ever taken a cooking class?",
    "Enjoy attending wine tastings?",
    "Have ever gone on a hiking trip?",
    "Enjoy stargazing?",
    "Have ever gone on a photography expedition?",
    "Enjoy attending cultural festivals?",
    "Have ever gone on a historical tour?",
    "Enjoy attending craft fairs or markets?",
    "Have ever tried meditation or yoga?",
    "Enjoy attending outdoor concerts or festivals?",
    "Have ever tried a new adventurous activity while traveling?"
] as const;


export const THIS_MUCH_QUESTIONS = [
    "Rate your level of satisfaction with your current job.",
    "How much do you trust the government?",
    "Rate your level of stress on a typical workday.",
    "How healthy do you perceive your lifestyle to be?",
    "How much do you enjoy spending time with your family?",
    "How confident are you in your decision-making abilities?",
    "How much do you enjoy trying new experiences?",
    "How much do you value education?",
    "How much do you feel you contribute to your community?",
    "How open-minded do you consider yourself to be?",
    "Rate your level of optimism about the future.",
    "How much do you enjoy spending time alone?",
    "How often do you feel stressed in social situations?",
    "How much do you feel you contribute to protecting the environment?",
    "How satisfied are you with your current living situation?",
    "Rate your level of enjoyment in trying new foods.",
    "How confident are you in your ability to learn new skills?",
    "Rate your level of excitement for upcoming holidays.",
    "How much do you trust your instincts in making decisions?",
    "Rate your level of contentment with your daily routine.",
    "How fulfilled do you feel in your hobbies or creative pursuits?",
    "Rate your level of anticipation for the changing seasons.",
    "How well do you feel you connect with nature?",
    "Rate your level of enjoyment in spending time with pets.",
    "How satisfied are you with your physical fitness level?",
    "Rate your level of curiosity about the world around you.",
    "How much do you enjoy spending time outdoors?",
    "Rate your level of appreciation for different forms of art.",
    "How connected do you feel to your local community?",
    "Rate your level of satisfaction with your social connections.",
    "How much do you enjoy learning about different cultures?",
    "Rate your level of relaxation during leisure activities.",
    "How satisfied are you with your current wardrobe?",
    "Rate your level of excitement for upcoming personal milestones.",
    "How much do you enjoy spending time in quiet reflection?",
    "Rate your level of enthusiasm for trying new hobbies.",
    "How satisfied are you with your personal growth and development?",
    "Rate your level of comfort in social settings.",
    "How much do you enjoy exploring new places?",
    "Rate your level of gratitude for the little things in life.",
    "How connected do you feel to your family and friends?",
    "Rate your level of enjoyment in helping others.",
    "Rate your level of comfort in expressing your emotions.",
    "How much do you enjoy listening to music?",
    "How much do you enjoy engaging in physical activity or exercise?",
    "Rate your level of excitement for upcoming personal projects or endeavors.",
    "How satisfied are you with your current level of organization and productivity?",
    "How much do you value spending time with loved ones?",
    "Rate your level of enthusiasm for trying new recipes or cooking techniques.",
    "How much do you enjoy spending time in nature, such as hiking or camping?",
    "Rate your level of confidence in expressing your creativity.",
    "How satisfied are you with your current financial situation?",
    "How much do you enjoy participating in cultural events or festivals?",
    "How much do you value opportunities for personal reflection and introspection?",
    "How much do you enjoy participating in recreational activities or hobbies?",
    "Rate your level of appreciation for art, such as paintings, sculptures, or performances.",
    "How much do you value having meaningful conversations with others?",
    "Rate your level of excitement for trying out new ice cream flavors.",
    "How satisfied are you with your ability to tell jokes and make people laugh?",
    "Rate your level of enjoyment in dancing like nobody's watching.",
    "Rate your level of enthusiasm for attending costume parties or themed events.",
    "How satisfied are you with your karaoke singing skills?",
    "How much do you enjoy celebrating silly holidays or quirky traditions?",
    "Rate your level of enjoyment in watching cheesy romantic comedies.",
    "How satisfied are you with your ability to create funny memes or jokes?",
    "Rate your level of excitement for dressing up in fun costumes during Halloween.",
    "Rate your level of enthusiasm for attending outdoor picnics or BBQs.",
    "Rate your level of enjoyment in playing with pets or animals.",
    "How much do you love indulging in guilty pleasure snacks or treats?",
    "Rate your level of excitement for attending amusement parks or carnivals.",
    "How satisfied are you with your ability to do silly impressions or accents?",
    "Rate your level of enjoyment in playing board games or card games.",
    "How much do you enjoy participating in random acts of kindness or generosity?"
] as const;


export const IMPERSIFACIONS_QUESTIONS = [
    "Mime trapped in an invisible box.",
    "Detective solving a mystery.",
    "Clumsy waiter serving dinner.",
    "News anchor reporting breaking news.",
    "Chef cooking in a busy kitchen.",
    "Mad scientist conducting an experiment.",
    "Cowboy riding a bucking bronco.",
    "Superhero rescuing a kitten from a tree.",
    "Tired parent trying to put a baby to sleep.",
    "Pirate searching for buried treasure.",
    "Circus performer walking a tightrope.",
    "Talk show host interviewing a celebrity.",
    "Mime trying to escape from an invisible box.",
    "Zombie searching for brains.",
    "Superhero flying through the sky.",
    "Magician performing a disappearing act.",
    "Robot malfunctioning and going haywire.",
    "Gardener planting seeds in a garden.",
    "Ninja sneaking through the shadows.",
    "Vampire avoiding sunlight.",
    "Rockstar performing on stage.",
    "Scientist conducting experiments in a lab.",
    "Firefighter rescuing people from a burning building.",
    "Clown performing at a birthday party.",
    "Spy on a secret mission.",
    "Chef cooking with exaggerated flair.",
    "Construction worker operating heavy machinery.",
    "Photographer capturing the perfect shot.",
    "Cat chasing a laser pointer.",
    "Alien abductee experiencing a probing.",
    "Time traveler trying to blend in with cavemen.",
    "Werewolf grooming itself during a full moon.",
    "Ghost haunting a refrigerator.",
    "Robot malfunctioning and doing the cha-cha.",
    "Mermaid trying to use a smartphone underwater.",
    "Zombie participating in a dance-off.",
    "Vampire trying to take a selfie without showing up in the mirror.",
    "Yeti trying to catch a taxi in the city.",
    "Troll attempting to use a computer.",
    "Sasquatch trying on fashionable clothes.",
    "Unicorn struggling to fit in at a normal horse stable.",
    "Goblin practicing yoga in a forest.",
    "Fairy trying to navigate a human-sized door.",
    "Witch brewing a potion with bizarre ingredients.",
    "Loch Ness Monster trying to hail a submarine.",
    "Cyclops trying to put on sunglasses.",
    "Frankenstein's monster learning to skateboard.",
    "Dinosaur trying to ride a bicycle.",
    "Kraken attempting to play the piano.",
    "Astronaut trying to eat floating food in space.",
    "Mime trapped in an invisible box on a windy day.",
    "Clown trying to juggle with oversized objects.",
    "Tourist taking a selfie with a landmark.",
    "Zombie participating in a zombie-themed dance competition.",
    "Scientist conducting experiments with unconventional ingredients.",
    "Actor auditioning for a role in a silent film.",
    "Chef cooking with exaggerated flair on a cooking show.",
    "Mime trying to escape from an invisible straightjacket.",
    "Robot learning to dance the robot.",
    "Superhero attempting to fly with a broken cape.",
    "Detective searching for clues with a magnifying glass.",
    "Mime trying to fix a broken imaginary vehicle.",
    "News reporter covering a hurricane while being blown away.",
    "Cowboy herding invisible cattle.",
    "Magician performing a magic trick gone wrong.",
    "Fisherman reeling in an imaginary big catch.",
    "Surfer riding an invisible wave.",
    "Photographer taking pictures of invisible subjects.",
    "Diver exploring an underwater cave system.",
    "Mime performing an invisible tightrope walk.",
    "Race car driver navigating an invisible race track.",
    "Athlete competing in a sport with invisible opponents.",
    "Gardener tending to an invisible garden.",
    "Astronomer discovering a new planet with an imaginary telescope.",
    "Puppeteer controlling an invisible marionette.",
    "Sculptor shaping an invisible masterpiece out of thin air.",
    "Acrobat performing on an invisible tightrope suspended in mid-air.",
    "Ghostbuster chasing an invisible ghost through a haunted house.",
    "Time traveler trying to fix an invisible time machine.",
    "Astronaut planting an invisible flag on a distant planet.",
    "Beekeeper tending to an invisible hive of bees.",
    "Samurai warrior dueling an invisible opponent with an imaginary sword.",
    "Street artist creating an invisible mural on a blank wall.",
    "Astronomer discovering an invisible comet streaking across the night sky.",
    "Mime navigating through an invisible maze with invisible walls.",
    "Farmer harvesting invisible crops in a field.",
    "Inventor testing out an invisible invention with unexpected results.",
    "Circus performer taming an invisible lion in the center ring.",
    "Explorer mapping out an invisible territory on an uncharted island.",
    "Stage magician performing a disappearing act without any props.",
    "Fairy sprinkling invisible magic dust to grant wishes.",
    "Archaeologist excavating an invisible ancient ruin.",
    "Samurai warrior meditating under an invisible cherry blossom tree.",
    "Pirate searching for buried treasure on an invisible island."
] as const;



export type YouGottaPointQuestion = typeof YOU_GOTTA_POINT_QUESTIONS[number];
export type FaceValueQuestion = typeof FACE_VALUE_QUESTIONS[number];
export type HandsOfTruthQuestion = typeof HANDS_OF_TRUTH_QUESTIONS[number];
export type NumberPressureQuestion = typeof NUMBER_PRESSURE_QUESTIONS[number];
export type ImpersifacionsQuestion = typeof IMPERSIFACIONS_QUESTIONS[number];
export type ThisMuchQuestion = typeof THIS_MUCH_QUESTIONS[number];

export type Question = YouGottaPointQuestion | FaceValueQuestion | HandsOfTruthQuestion | NumberPressureQuestion | ImpersifacionsQuestion | ThisMuchQuestion | 'PLACEHOLDER';

export const GAME_TYPES = ['You Gotta Point', 'Face Value', 'Hands of Truth', 'Number Pressure', 'Impersifacions', 'This Much', 'None'] as const;

export type GameType = typeof GAME_TYPES[number];